services:
  mc-router-scaler:
    image: ghcr.io/lucsoft/mc-router-scaler:0.1.1
    build:
      context: tools/mc-router-scaler
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
  pkl-packages:
    image: ghcr.io/lucsoft/pkl-packages:latest
    build:
      context: pkl-packages
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
