# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/isindir.github.com/sopssecret_v1alpha3.json
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: curseforge-apikey
  namespace: minecraft
spec:
  secretTemplates:
    - name: curseforge-apikey
      stringData:
        CF_API_KEY: ENC[AES256_GCM,data:TwlCIDKKfKXWQm1MS/T0lPpcyCF3s7ECqXD/BM4UOzLLqiw8m4bJrwzFwHbLPnYHlvJk9AyjG0+cfu7V,iv:GKV5PxhNy1bhf7nCUeIGmH+r+QuQVWrSLStJ0ngZw0I=,tag:9y7BISMxGaHcfzxlKs7A1Q==,type:str]
sops:
  encrypted_suffix: Data
  gcp_kms:
    - created_at: "2026-06-06T10:24:01Z"
      enc: CiQAQ9B597MWjA5Eg7lySw48L19nLdbraWFXUVKi9gtYUAXi6cASSQCloZdxOtPitYWt7IV9R6dKVfKVU1FH4wHy5k2ULY55dxH6HAjdswdWi8lT12D1XZuL5OysCxkjNwNfpi/1icrNIybB7soU70U=
      resource_id: projects/idyllic-pottery-414714/locations/global/keyRings/sops/cryptoKeys/sops-key
  lastmodified: "2026-06-06T11:26:09Z"
  mac: ENC[AES256_GCM,data:sviBRRTlCL0qY/604bklMGkNvPKCkwUsZGk6/2+Q70oy26ImgTPb7pHmCw18kpW0hEDQrZGpePOTz/2G7B9u0l1lwBlrd/AqKiJSkqyrKyEjMBqqJnGwXDoAgO7FLkM4Osm7WzajopNxG6fQnmSaniVQU+7AzECGNDhtgJEpAhg=,iv:brBHSClotk4LDULNh7tKDkYiuarJ73CUph3Yo0CgElI=,tag:mUygWMRwP2r8LagdkJk97A==,type:str]
  version: 3.13.1
