# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/isindir.github.com/sopssecret_v1alpha3.json
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mqtt2prometheus-auth
    namespace: monitoring
spec:
    secretTemplates:
        - name: mqtt2prometheus-auth
          stringData:
            MQTT2PROM_MQTT_USER: ENC[AES256_GCM,data:2Mcf6hoKkNoSyt1Qxt0l,iv:ktH5aphJQOLvwBMSm2INZDdMTYMs3UrQsF4ZnMtk3qQ=,tag:xJIMdkA+AxL3rSAJuQl7Jg==,type:str]
            MQTT2PROM_MQTT_PASSWORD: ENC[AES256_GCM,data:dmUm3slFa//RMHZ5TbjhwdBsBsV3ltxarO8hniqOazc=,iv:D3vlzHEzdLXpGbuJGxLyDrvsVHMjjGx8lyTAnr0nyos=,tag:vNyx7r+GAWD+yRSVeKbvNg==,type:str]
sops:
    encrypted_suffix: Data
    gcp_kms:
        - created_at: "2026-08-07T12:25:03Z"
          enc: CiQAQ9B592GG+E7pc2Bai1QF6ngpKI8aVSS/ihN69bHlG9lObG4SSQCloZdxhIbGK3KzrNjtOG8ZgmbqTxwOp7uwEjXALcnh5KCgpgBIAcgKYWj58mjhEETx/E8TnywcyPJhfmBjUmFwBZE2gavx2pE=
          resource_id: projects/idyllic-pottery-414714/locations/global/keyRings/sops/cryptoKeys/sops-key
    lastmodified: "2026-08-07T12:25:04Z"
    mac: ENC[AES256_GCM,data:DxVlPTjop5u7I4v6/+otRZEBHT8nBmqBq6M6jK0+58w5r5vUj+YhWx1yJV56tcBwe6OlIuQE3QJ3MPiwNeC/iRViRQgKysCk3tLPUzO0upA9haIP00HXUFgJuVZAymRgWgAyrrTJA0oj0+CsCPmfbYUSTtXypKR4ZJ+Xac84O4c=,iv:aNHY+LOxzeSLxYfjeUfEWzQwhkdW7uh2FhDCMm/vJsk=,tag:/1g/MpWcR4GzvPmK4XQvpA==,type:str]
    version: 3.13.3
